### ISSUE TITLE
她俩算是老司机了

### ISSUE THREAD

**Issue by izhangzhihao** [wemakebug/how-to-send-pr#2]
能不能把“她”改了 @guokeke

**Comment by izhangzhihao** [comment]
话说你这在哪啊
![image](https://cloud.githubusercontent.com/assets/12044174/16827807/9c7a0424-49bc-11e6-92af-5a70039d84f9.png)

**Comment by izhangzhihao** [comment]
![Uploading image.png…]()

**Comment by guokeke** [comment]
阿里云。。
